from code_hosts.api.views.integration import (
    WorkspaceIntegrationAvailableRepositoriesView,
    WorkspaceIntegrationCreateView,
    WorkspaceIntegrationDeleteView,
    WorkspaceIntegrationListView,
    WorkspaceIntegrationUpdateView,
    WorkspaceRepositoryConnectView,
    WorkspaceRepositoryDeleteView,
    WorkspaceRepositoryListView,
    WorkspaceRepositoryMergeRequestListView,
    WorkspaceRepositoryMergeRequestSyncView,
)
from code_hosts.api.views.workspace import (
    WorkspaceCreateView,
    WorkspaceDeleteView,
    WorkspaceListView,
    WorkspaceUpdateView,
)
from django.urls import path
from reviews.api.views import (
    ReviewRunCancelView,
    ReviewRunCommentsView,
    ReviewRunCreateView,
    ReviewRunDetailView,
    ReviewRunListView,
    ReviewRunPublishView,
    ReviewRunRerunView,
)

urlpatterns = [
    path("create/", WorkspaceCreateView.as_view(), name="workspace-create"),
    path("list/", WorkspaceListView.as_view(), name="workspace-list"),
    path(
        "<int:workspace_id>/delete/",
        WorkspaceDeleteView.as_view(),
        name="workspace-delete",
    ),
    path(
        "<int:workspace_id>/update/",
        WorkspaceUpdateView.as_view(),
        name="workspace-update",
    ),
    # Integration URLs
    path(
        "<int:workspace_id>/integrations/create/",
        WorkspaceIntegrationCreateView.as_view(),
        name="workspace-integration-create",
    ),
    path(
        "<int:workspace_id>/integrations/list/",
        WorkspaceIntegrationListView.as_view(),
        name="workspace-integration-list",
    ),
    path(
        "<int:workspace_id>/integrations/<int:integration_id>/repositories/available/",
        WorkspaceIntegrationAvailableRepositoriesView.as_view(),
        name="workspace-integration-repositories-available",
    ),
    path(
        "<int:workspace_id>/integrations/<int:integration_id>/update/",
        WorkspaceIntegrationUpdateView.as_view(),
        name="workspace-integration-update",
    ),
    path(
        "<int:workspace_id>/integrations/<int:integration_id>/delete/",
        WorkspaceIntegrationDeleteView.as_view(),
        name="workspace-integration-delete",
    ),
    path(
        "<int:workspace_id>/repositories/connect/",
        WorkspaceRepositoryConnectView.as_view(),
        name="workspace-repositories-connect",
    ),
    path(
        "<int:workspace_id>/repositories/list/",
        WorkspaceRepositoryListView.as_view(),
        name="workspace-repositories-list",
    ),
    path(
        "<int:workspace_id>/repositories/<int:repository_id>/delete/",
        WorkspaceRepositoryDeleteView.as_view(),
        name="workspace-repositories-delete",
    ),
    path(
        "<int:workspace_id>/repositories/<int:repository_id>/merge-requests/list/",
        WorkspaceRepositoryMergeRequestListView.as_view(),
        name="workspace-repository-merge-requests-list",
    ),
    path(
        "<int:workspace_id>/repositories/<int:repository_id>/merge-requests/sync/",
        WorkspaceRepositoryMergeRequestSyncView.as_view(),
        name="workspace-repository-merge-requests-sync",
    ),
    path(
        "<int:workspace_id>/merge-requests/<int:mr_id>/reviews/run/",
        ReviewRunCreateView.as_view(),
        name="workspace-mr-review-run",
    ),
    path(
        "<int:workspace_id>/merge-requests/<int:mr_id>/reviews/list/",
        ReviewRunListView.as_view(),
        name="workspace-mr-review-list",
    ),
    path(
        "<int:workspace_id>/merge-requests/<int:mr_id>/reviews/<int:review_run_id>/detail/",
        ReviewRunDetailView.as_view(),
        name="workspace-mr-review-detail",
    ),
    path(
        "<int:workspace_id>/merge-requests/<int:mr_id>/reviews/<int:review_run_id>/comments/",
        ReviewRunCommentsView.as_view(),
        name="workspace-mr-review-comments",
    ),
    path(
        "<int:workspace_id>/merge-requests/<int:mr_id>/reviews/<int:review_run_id>/rerun/",
        ReviewRunRerunView.as_view(),
        name="workspace-mr-review-rerun",
    ),
    path(
        "<int:workspace_id>/merge-requests/<int:mr_id>/reviews/<int:review_run_id>/cancel/",
        ReviewRunCancelView.as_view(),
        name="workspace-mr-review-cancel",
    ),
    path(
        "<int:workspace_id>/merge-requests/<int:mr_id>/reviews/<int:review_run_id>/publish/",
        ReviewRunPublishView.as_view(),
        name="workspace-mr-review-publish",
    ),
]
