# Generated by Django 5.2.9 on 2025-12-03 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeHostIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название интеграции, отображаемое пользователю",
                        max_length=255,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("gitlab", "GitLab"), ("github", "GitHub")],
                        max_length=20,
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        default="https://gitlab.com",
                        help_text="Базовый URL сервера (для self-hosted GitLab)",
                    ),
                ),
                ("access_token", models.CharField(max_length=255)),
                (
                    "refresh_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Интеграция с Git-сервисом",
                "verbose_name_plural": "Интеграции с Git-сервисами",
            },
        ),
        migrations.CreateModel(
            name="CommitAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(db_index=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Автор коммитов",
                "verbose_name_plural": "Авторы коммитов",
                "unique_together": {("name", "email")},
            },
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="ID репозитория в GitLab/GitHub", max_length=255
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "full_path",
                    models.CharField(
                        help_text="namespace/project_name", max_length=512
                    ),
                ),
                ("default_branch", models.CharField(default="main", max_length=255)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repositories",
                        to="code_hosts.codehostintegration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Репозиторий",
                "verbose_name_plural": "Репозитории",
                "unique_together": {("integration", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="codehostintegration",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="integrations",
                to="code_hosts.workspace",
            ),
        ),
        migrations.CreateModel(
            name="MergeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="ID MR/PR в GitLab/GitHub", max_length=255
                    ),
                ),
                (
                    "iid",
                    models.CharField(
                        help_text="Номер MR в проекте (IID / номер PR)", max_length=50
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("author_name", models.CharField(max_length=255)),
                ("author_username", models.CharField(blank=True, max_length=255)),
                ("source_branch", models.CharField(max_length=255)),
                ("target_branch", models.CharField(max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("merged", "Merged"),
                        ],
                        max_length=20,
                    ),
                ),
                ("web_url", models.URLField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merge_requests",
                        to="code_hosts.repository",
                    ),
                ),
            ],
            options={
                "verbose_name": "Merge Request / Pull Request",
                "verbose_name_plural": "Merge Requests / Pull Requests",
                "ordering": ["-created_at"],
                "unique_together": {("repository", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="Commit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("hash", models.CharField(db_index=True, max_length=64)),
                ("message", models.TextField()),
                ("authored_date", models.DateTimeField()),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commits",
                        to="code_hosts.commitauthor",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commits",
                        to="code_hosts.repository",
                    ),
                ),
            ],
            options={
                "verbose_name": "Коммит",
                "verbose_name_plural": "Коммиты",
                "ordering": ["-authored_date"],
                "unique_together": {("repository", "hash")},
            },
        ),
        migrations.CreateModel(
            name="WorkspaceMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("member", "Member"),
                            ("viewer", "Viewer"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="code_hosts.workspace",
                    ),
                ),
            ],
            options={
                "unique_together": {("workspace", "user")},
            },
        ),
    ]
