# Generated by Django 5.2.9 on 2025-12-03 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_hosts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="is_connected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="repository",
            name="web_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workspace_repositories",
                to="code_hosts.workspace",
            ),
        ),
    ]
