# Generated by Django 5.2.9 on 2025-12-03 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("code_hosts", "0002_repository_is_connected_repository_web_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repository",
            name="is_connected",
        ),
        migrations.RemoveField(
            model_name="repository",
            name="web_url",
        ),
        migrations.RemoveField(
            model_name="repository",
            name="workspace",
        ),
    ]
