# Generated by Django 5.2.9 on 2025-12-03 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("code_hosts", "0003_remove_repository_is_connected_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название интеграции, отображаемое пользователю",
                        max_length=255,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI ChatGPT"),
                            ("deepseek", "DeepSeek"),
                            ("ollama", "Ollama (Local)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        blank=True,
                        help_text="Базовый URL API. Для Ollama — http://localhost:11434",
                        null=True,
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        help_text="API ключ для OpenAI / DeepSeek. Для Ollama не нужен.",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Название модели, напр. 'gpt-4o', 'deepseek-chat', 'llama3'",
                        max_length=255,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Кто создал эту интеграцию и управляет ей",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_integrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Интеграция LLM",
                "verbose_name_plural": "Интеграции LLM",
            },
        ),
        migrations.CreateModel(
            name="WorkspaceLLMIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_bindings",
                        to="llm.llmintegration",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_bindings",
                        to="code_hosts.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM-интеграция в workspace",
                "verbose_name_plural": "LLM-интеграции в workspace",
                "unique_together": {("workspace", "integration")},
            },
        ),
    ]
