# Generated by Django 5.2.9 on 2026-01-27 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("code_hosts", "0003_remove_repository_is_connected_and_more"),
        ("llm", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("input_payload", models.JSONField(blank=True, default=dict)),
                ("raw_output", models.TextField(blank=True)),
                ("structured_output", models.JSONField(blank=True, default=dict)),
                ("model_name", models.CharField(blank=True, max_length=255)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("max_tokens", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "llm_integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_runs",
                        to="llm.llmintegration",
                    ),
                ),
                (
                    "merge_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_runs",
                        to="code_hosts.mergerequest",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_review_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Review run",
                "verbose_name_plural": "Review runs",
                "ordering": ["-queued_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=20,
                    ),
                ),
                (
                    "comment_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("code_smell", "Code Smell"),
                            ("bug", "Bug"),
                            ("security", "Security"),
                            ("performance", "Performance"),
                            ("style", "Style"),
                            ("tests", "Tests"),
                            ("documentation", "Documentation"),
                        ],
                        db_index=True,
                        default="general",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField()),
                ("file_path", models.CharField(blank=True, max_length=1024)),
                ("line_start", models.IntegerField(blank=True, null=True)),
                ("line_end", models.IntegerField(blank=True, null=True)),
                ("suggestion", models.TextField(blank=True)),
                ("posted_to_vcs", models.BooleanField(default=False)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="reviews.reviewrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review comment",
                "verbose_name_plural": "Review comments",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="reviewrun",
            index=models.Index(
                fields=["merge_request", "status"],
                name="reviews_rev_merge_r_221b20_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewrun",
            index=models.Index(
                fields=["llm_integration", "status"],
                name="reviews_rev_llm_int_9996c9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewcomment",
            index=models.Index(
                fields=["review_run", "severity"], name="reviews_rev_review__c4efbf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewcomment",
            index=models.Index(
                fields=["review_run", "comment_type"],
                name="reviews_rev_review__89b3bf_idx",
            ),
        ),
    ]
